### ISSUE TITLE
chocolatey\chocolatey\chocolatey\.... temp download paths

### ISSUE THREAD

**Issue by flcdrg** [mwrock/boxstarter#241]
2.9.2 - seeing packages getting downloaded into weird folders (and then failing).

C:\Users\dgardiner\AppData\Local\Temp\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\.squirrel-lock-0205C670A9D776F56D17A8FB985A520ADEE61F89: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

**Comment by flcdrg** [comment]
Seems like each package is going one level deeper :-)

**Comment by gep13** [comment]
You can never have to much `chocolatey`!

Ok, I will leave now...

😄

**Comment by mwrock** [comment]
I have submitted https://github.com/chocolatey/choco/pull/1211 to fix this issue.

**Comment by mwrock** [comment]
Just released this fix on 2.9.5

**Comment by flcdrg** [comment]
Still seeing this in 2.9.5 :-(

**Comment by flcdrg** [comment]
Just guessing, but could it be that config.CacheLocation.EndsWith("chocolatey") would be false if CacheLocation had a trailing slash/backslash?

**Comment by flcdrg** [comment]
Raised https://github.com/chocolatey/choco/issues/1231

**Comment by mwrock** [comment]
see https://github.com/chocolatey/choco/pull/1232. I tested this build against boxstarter and the nested directories appear to be gone.

**Comment by mwrock** [comment]
Reopening this until the above is released

**Comment by KZeronimo** [comment]
Ugg - sorry I missed this - and I looked at this one the other day and chuckled about

> You can never have to much chocolatey!

**Comment by mwrock** [comment]
no worries. this issue was closed which is probably why you missed it :)

**Comment by batzen** [comment]
https://github.com/chocolatey/choco/pull/1233 is the correct PR, just for reference.

**Comment by flcdrg** [comment]
Confirmed that this is now resolved

**Comment by amaau** [comment]
nope not resolved yet,
boxstarter 2.10.3 + choco 0.10.7 still have this problem

**Comment by mwrock** [comment]
yes we had to revert to choco 0.10.5 which "rebroke" this but fixed larger problems.

**Comment by amaau** [comment]
but current (2.10.3) boxstarter installs choco 0.10.7, at least that's what the log says

**Comment by mwrock** [comment]
boxstarter doesn't install chocolatey unless your script installs it. It just calls into a chocolatey dll.

**Comment by mwrock** [comment]
oh maybe you are referring to the bootstrapper which does install the latest choco if it is not installed in order to install boxstarter. That would install 0.10.7 but it does not use it in boxstarter runs.

**Comment by amaau** [comment]
right, sorry, i did refer to the bootstrapper

**Comment by ferventcoder** [comment]
I thought I had seen this as well - should have linked the two.  https://github.com/chocolatey/choco/pull/1233#issuecomment-318479205

**Comment by ericrlarson** [comment]
Matt, any idea when a new version of Boxstarter will be released that will have a version of Chocolatey which addresses this issue?  We are unable to use boxstarter with this issue in it. :(

**Comment by Sebbl22** [comment]
Are there any known workarounds? Can i reset the Cach Path after each package install?

**Comment by ericrlarson** [comment]
That did not work for me.  If you try and it works let me know!

**Comment by kirannhegde** [comment]
@mwrock  Hello Matt, I am using the latest version of  Boxstarter bootstrapper, that installs the latest version of Chocolatey. I am seeing this issue as well when i try to install a series of packages using the text file on Git gist. Is there an easy way to workaround this issue?

**Comment by mwrock** [comment]
not that I am aware of @kirannhegde but have not had time to investigate

**Comment by kirannhegde** [comment]
I worked around this issue by using an alternative cache location, instead of the user temp directory. Basically , for each choco install, i explicitly use an alternative cache location as follows:
**cinst 7zip --version 9.22 --source https://abc.com/ --cacheLocation "$env:SystemDrive\TCAgentSetupCache"**

Hope this helps.

@Sebbl22 @ericrlarson

**Comment by Sebbl22** [comment]
Thanks @kirannhegde. Your solution worked for me.

**Comment by flcdrg** [comment]
This is still causing problems, and the workaround isn't working for me with the latest BoxStarter. Even though cacheLocation is being passed in, Chocolatey is still using %TEMP% which has the chocolatey\chocolatey\chocolatey problem :-(

**Comment by flcdrg** [comment]
Looks like if you apply --cache-location to *every* choco call in your BoxStarter script, you might be ok. That includes `choco pin`, and windows features

**Comment by Oxymoron290** [comment]
im stuck, help

**Comment by pauby** [comment]
@Oxymoron290 What are you stuck with?

**Comment by Oxymoron290** [comment]
This problem with infinite chocolatey folders in cache. I've tried adding `--cacheLocation "$env:userprofile\AppData\Local\ChocoCache"` at the end of all `cinst` statements and the problem persists
![image](https://user-images.githubusercontent.com/2234419/46919802-5a3ae800-cfaa-11e8-958c-198cbcfd20e4.png)

**Comment by Oxymoron290** [comment]
Yes, it is working now.

**Comment by ctmcisco** [comment]
thing only began to happen when I repaved my machine using Boxstarter. Is this a boxstarter issue as I don't seem to have this issue when running Chocolatey only?

**Comment by ctmcisco** [comment]
I see, so best thing to do is either run with the work around for now as suggested by @neilkidd or only use Chocolatey?

**Comment by flcdrg** [comment]
Yes. (Credit to @kirannhegde)..

It only becomes a problem if you exceed a certain number of packages. Some of my Boxstarter scripts get by without it, but the longer ones require the workaround for now.

https://gist.github.com/flcdrg/87802af4c92527eb8a30

**Comment by ctmcisco** [comment]
great catch @kirannhegde !

The below is what I am doing for now and every time I this the fails are happen randomly between packages. So I think adding the Temp cache to all is the safest bet.

I like your cleaner look of dropping the cache location in a variable.

Thanks. Now I have to clean up the script a bit. Arg I should have checked in before trying to trouble on my own. Lost some time.

Thanks again!


choco upgrade --cacheLocation="$ChocoCachePath" googlechrome -dy
choco upgrade --cacheLocation="$ChocoCachePath" firefox -dy
choco upgrade --cacheLocation="$ChocoCachePath" skype -dy
choco upgrade --cacheLocation="$ChocoCachePath" ditto -dy
choco upgrade --cacheLocation="$ChocoCachePath" keepass.install -dy
choco upgrade --cacheLocation="$ChocoCachePath" flashplayerplugin -dy
choco upgrade --cacheLocation="$ChocoCachePath" sysinternals -dy
choco upgrade --cacheLocation="$ChocoCachePath" winrar -dy
choco upgrade --cacheLocation="$ChocoCachePath" teamviewer -dy
choco upgrade --cacheLocation="$ChocoCachePath" notepadplusplus -dy
choco upgrade --cacheLocation="$ChocoCachePath" filezilla -dy
choco upgrade --cacheLocation="$ChocoCachePath" angryip -dy
choco upgrade --cacheLocation="$ChocoCachePath" putty -dy
choco upgrade --cacheLocation="$ChocoCachePath" winscp -dy
choco upgrade --cacheLocation="$ChocoCachePath" nmap -dy
choco upgrade --cacheLocation="$ChocoCachePath" mRemoteNG -dy
choco upgrade --cacheLocation="$ChocoCachePath" openssh -dy
choco upgrade --cacheLocation="$ChocoCachePath" vnc-viewer-plus -dy
choco upgrade --cacheLocation="$ChocoCachePath" powershell-core -dy
choco upgrade --cacheLocation="$ChocoCachePath" markdownmonster -dy
choco upgrade --cacheLocation="$ChocoCachePath" git -dy
choco upgrade --cacheLocation="$ChocoCachePath" vscode -dy

**Comment by pauby** [comment]
Need to upgrade chocolatey lib to a later version - need to determine which one. This [comment](https://github.com/chocolatey/choco/issues/1661#issuecomment-455400811) suggests it's fixed in 0.10.4.

**Comment by jamie-tillman** [comment]
This "increasing chocolatey temp path" happened to me to today when running this gist using the current downloadable Boxstarter:
https://gist.github.com/jamie-tillman/a375037784d6874a77a6049f56fd53bc

**Comment by me-kell** [comment]
It is the dll `chocolatey.dll` packaged with Boxstarter that changes the variable `$env:temp`.
Replacing the packaged `chocolatey.dll` with a new version from `chocolatey.lib.0.10.15\lib\chocolatey.dll` returns the `$env:temp` unchanged.

See my comments on https://github.com/chocolatey/boxstarter/issues/442#issuecomment-707600051

**Comment by pauby** [comment]
@me-kell Can we keep the comments on your issue?

Just for clarity, replacing the `chocolatey.dll` is not an option at this point.

**Comment by me-kell** [comment]
@pauby Do you mean not writing the comments here but only in the issue #442 ?

**Comment by pauby** [comment]
@me-kell Yes. That way we keep everything relevant to that issue and the discussion only needs to happen once. Your issue is linked here so people can refer to it.

**Comment by me-kell** [comment]
@pauby Thank very much you for the hint.

**Comment by Jawabiscuit** [comment]
Greetings, I thought I'd submit a bug but seems this is a very well known issue. I _think_ I got around the issue by setting the [chocolatey config cache path](https://docs.chocolatey.org/en-us/guides/usage/change-cache). Seems very sad to have to resort to workarounds such as putting `--cacheLocation` everywhere e.g. https://gist.github.com/flcdrg/87802af4c92527eb8a30. 

There's a handy tool called [choco-cleaner](https://chocolatey.org/packages/choco-cleaner) in case people reading this haven't heard of it.  A sprinkling of `choco-cleaner` in long install scripts seems to be working much better for me. Installed early on with: `choco install choco-cleaner; refreshenv`.
